services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    ports:
     - "3100:3100"  # utile pour tests locaux
    networks:
     - monitoring

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    restart: always
    ports:
     - "3000:3000"  # utile pour accès direct
    environment:
     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
     - GF_DATABASE_TYPE=postgres
     - GF_DATABASE_HOST=postgres:5432
     - GF_DATABASE_NAME=grafana
     - GF_DATABASE_USER=grafana
     - GF_DATABASE_PASSWORD=secret
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`monitoring.enhanced-git.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=monitoring"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitoring

volumes:
  pgdata:

networks:
  monitoring:
    external: true
  traefik:
    external: true